import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Generated by Playwright after an e2e run; linting their bundled third-party JS creates
    // irrelevant warnings and makes the quality gate order-dependent.
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
