package com.ledgerly.api.alert;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/** Per-user read/dismiss state for an {@link Alert}. Never mutates the alert snapshot itself.
 *
 * <p>Implements {@link Persistable} because the composite key is assigned by the application, not
 * generated by the database: without it, Spring Data guesses "new" from whether the id is null,
 * which is never true here, so every {@code save()} would take Hibernate's merge path (a SELECT
 * followed by an UPDATE) instead of an INSERT — silently turning an attempted duplicate insert into
 * a no-op update rather than surfacing the unique-constraint violation. */
@Entity
@Table(name = "alert_state")
@IdClass(AlertStateId.class)
public class AlertState implements Persistable<AlertStateId> {

  @Id
  @Column(name = "alert_id")
  private UUID alertId;

  @Id
  @Column(name = "user_id")
  private UUID userId;

  @Column(name = "read_at")
  private Instant readAt;

  @Column(name = "dismissed_at")
  private Instant dismissedAt;

  @Transient
  private boolean isNew = true;

  protected AlertState() {}

  public AlertState(UUID alertId, UUID userId) {
    this.alertId = alertId;
    this.userId = userId;
  }

  @Override
  public AlertStateId getId() {
    return new AlertStateId(alertId, userId);
  }

  @Override
  public boolean isNew() {
    return isNew;
  }

  @PostLoad
  @PostPersist
  void markNotNew() {
    isNew = false;
  }

  public UUID getAlertId() {
    return alertId;
  }

  public UUID getUserId() {
    return userId;
  }

  public Instant getReadAt() {
    return readAt;
  }

  public Instant getDismissedAt() {
    return dismissedAt;
  }

  public void markRead() {
    if (readAt == null) {
      readAt = Instant.now();
    }
  }

  public void markDismissed() {
    if (dismissedAt == null) {
      dismissedAt = Instant.now();
    }
  }
}
