export type DocumentStatus = "PENDING" | "PROCESSING" | "EXTRACTED" | "NEEDS_REVIEW" | "FAILED";

export interface UploadedDocument {
  id: string;
  filename: string;
  contentType: string;
  sizeBytes: number;
  status: DocumentStatus;
  failureReason: string | null;
}

export type UploadResult =
  | { ok: true; document: UploadedDocument }
  | { ok: false; status: number; message: string };

/**
 * `POST /api/v1/documents` is a mutating endpoint behind `IdempotencyFilter` — it 400s without
 * an `Idempotency-Key` header. The key is generated by the caller (not in here) and must be
 * fresh per call to this function; there is currently no retry path that calls this twice for
 * the same attempt, but if one is added, it needs to pass the *same* key back in, not call
 * `uploadDocument` again with a new one — otherwise a flaky-network retry double-posts instead
 * of being deduplicated by the api.
 */
export async function uploadDocument(
  file: File,
  idempotencyKey: string,
): Promise<UploadResult> {
  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch("/api/documents", {
    method: "POST",
    headers: { "Idempotency-Key": idempotencyKey },
    body: formData,
  });

  if (!response.ok) {
    let message = "Upload failed. Please try again.";
    try {
      const problem = (await response.json()) as { detail?: string };
      message = problem.detail ?? message;
    } catch {
      // Non-JSON error body — keep the generic message.
    }
    return { ok: false, status: response.status, message };
  }

  return { ok: true, document: (await response.json()) as UploadedDocument };
}
