export type PolicyDocumentStatus = "PENDING" | "PROCESSING" | "EMBEDDED" | "FAILED";

export interface PolicyDocument {
  id: string;
  filename: string;
  status: PolicyDocumentStatus;
  failureReason: string | null;
  createdAt: string;
  chunkCount: number;
}

export interface PolicyChunk {
  index: number;
  text: string;
}

const KNOWN_STATUSES: readonly PolicyDocumentStatus[] = [
  "PENDING",
  "PROCESSING",
  "EMBEDDED",
  "FAILED",
];

function isKnownStatus(value: unknown): value is PolicyDocumentStatus {
  return typeof value === "string" && (KNOWN_STATUSES as readonly string[]).includes(value);
}

/**
 * Parses one policy document from the API. An unrecognized `status` value is a parse failure —
 * never rendered raw — so a future API status this client hasn't been taught degrades to an
 * explicit error rather than a chip nobody wrote copy for.
 */
export function parsePolicyDocument(raw: unknown): PolicyDocument | { error: string } {
  if (typeof raw !== "object" || raw === null) {
    return { error: "Policy document payload was not an object" };
  }
  const record = raw as Record<string, unknown>;
  if (typeof record.id !== "string" || typeof record.filename !== "string") {
    return { error: "Policy document is missing id or filename" };
  }
  if (!isKnownStatus(record.status)) {
    return { error: `Unknown policy document status: ${String(record.status)}` };
  }
  if (typeof record.createdAt !== "string") {
    return { error: "Policy document is missing createdAt" };
  }
  const chunkCount = typeof record.chunkCount === "number" ? record.chunkCount : 0;
  const failureReason = typeof record.failureReason === "string" ? record.failureReason : null;

  return {
    id: record.id,
    filename: record.filename,
    status: record.status,
    failureReason,
    createdAt: record.createdAt,
    chunkCount,
  };
}

export function parsePolicyDocuments(raw: unknown): PolicyDocument[] | { error: string } {
  if (!Array.isArray(raw)) {
    return { error: "Policy document list payload was not an array" };
  }
  const documents: PolicyDocument[] = [];
  for (const entry of raw) {
    const parsed = parsePolicyDocument(entry);
    if ("error" in parsed) {
      return parsed;
    }
    documents.push(parsed);
  }
  return documents;
}

export function parsePolicyChunk(raw: unknown): PolicyChunk | { error: string } {
  if (typeof raw !== "object" || raw === null) {
    return { error: "Policy chunk payload was not an object" };
  }
  const record = raw as Record<string, unknown>;
  if (typeof record.index !== "number" || typeof record.text !== "string") {
    return { error: "Policy chunk is missing index or text" };
  }
  return { index: record.index, text: record.text };
}

export function parsePolicyChunks(raw: unknown): PolicyChunk[] | { error: string } {
  if (!Array.isArray(raw)) {
    return { error: "Policy chunk list payload was not an array" };
  }
  const chunks: PolicyChunk[] = [];
  for (const entry of raw) {
    const parsed = parsePolicyChunk(entry);
    if ("error" in parsed) {
      return parsed;
    }
    chunks.push(parsed);
  }
  return chunks;
}

export type UploadPolicyResult =
  | { ok: true; document: PolicyDocument }
  | { ok: false; status: number; message: string };

/**
 * `POST /api/v1/policies` is synchronous and does not return until the outcome is final
 * (`EMBEDDED` with its chunks persisted, or `FAILED`) — this call genuinely takes several
 * seconds, it is not a fire-and-forget kickoff. Behind `IdempotencyFilter`, like
 * `uploadDocument`; the key is generated by the caller and must be fresh per attempt.
 */
export async function uploadPolicyDocument(
  file: File,
  idempotencyKey: string,
): Promise<UploadPolicyResult> {
  const formData = new FormData();
  formData.append("file", file);

  let response: Response;
  try {
    response = await fetch("/api/policies", {
      method: "POST",
      headers: { "Idempotency-Key": idempotencyKey },
      body: formData,
    });
  } catch {
    return { ok: false, status: 0, message: "We couldn't reach Ledgerly. The file was not uploaded." };
  }

  if (!response.ok) {
    let message =
      response.status === 415
        ? "Only PDF documents can be indexed. This file was not uploaded."
        : "The upload did not complete. Please try again.";
    try {
      const problem = (await response.json()) as { detail?: string };
      message = problem.detail ?? message;
    } catch {
      // Non-JSON error body — keep the status-derived message.
    }
    return { ok: false, status: response.status, message };
  }

  const payload = await response.json();
  const parsed = parsePolicyDocument(payload);
  if ("error" in parsed) {
    return { ok: false, status: 502, message: "The server returned an unreadable response." };
  }
  return { ok: true, document: parsed };
}
